//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicloVidaAltoValor.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CicloVidaAltoValor.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha inválida..
        /// </summary>
        public static string CampaignInvalid {
            get {
                return ResourceManager.GetString("CampaignInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não possui acesso a este segmento..
        /// </summary>
        public static string ClientUnauthorized {
            get {
                return ResourceManager.GetString("ClientUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido..
        /// </summary>
        public static string CPFInvalid {
            get {
                return ResourceManager.GetString("CPFInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento com intervalo inválido..
        /// </summary>
        public static string DateBirthDateInvalid {
            get {
                return ResourceManager.GetString("DateBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar o login..
        /// </summary>
        public static string ErrorOnLogin {
            get {
                return ResourceManager.GetString("ErrorOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar seu desejo..
        /// </summary>
        public static string ErrorOnMakeWish {
            get {
                return ResourceManager.GetString("ErrorOnMakeWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível completar seu cadastro..
        /// </summary>
        public static string ErrorOnRegisterUpdate {
            get {
                return ResourceManager.GetString("ErrorOnRegisterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo inválido..
        /// </summary>
        public static string LengthInvalid {
            get {
                return ResourceManager.GetString("LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não participante da promoção..
        /// </summary>
        public static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É Obrigatório Aceitar o Programa Dotz para prosseguir..
        /// </summary>
        public static string OptinRequired {
            get {
                return ResourceManager.GetString("OptinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar pelo menos um telefone..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto inválido.
        /// </summary>
        public static string ProductInvalid {
            get {
                return ResourceManager.GetString("ProductInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; deve ser informado..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado inválido..
        /// </summary>
        public static string StateInvalid {
            get {
                return ResourceManager.GetString("StateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já realizou o resgate.
        /// </summary>
        public static string UserAlreadyRedemption {
            get {
                return ResourceManager.GetString("UserAlreadyRedemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; com o valor: &apos;{PropertyValue}&apos; é inválido..
        /// </summary>
        public static string ValueInvalid {
            get {
                return ResourceManager.GetString("ValueInvalid", resourceCulture);
            }
        }
    }
}
