
USE DotzApp
GO


CREATE TABLE [CPR_CAMPANHA_USUARIO_ACESSO] (
	[CPR_CAMPANHA_USUARIO_ACESSO_ID] INT PRIMARY KEY IDENTITY(1,1),
	[CPR_USUARIO_ID] INT NOT NULL,
	[DATA_CRIACAO] DATETIME DEFAULT(GETDATE()) NOT NULL,
	CONSTRAINT [FK_CPR_CAMPANHA_USUARIO_ACESSO_CPR_USUARIO] FOREIGN KEY([CPR_USUARIO_ID]) REFERENCES [dbo].[CPR_USUARIO] ([CPR_USUARIO_ID])
);



CREATE TABLE [dbo].[CPR_PRODUTO_CAMPANHA] (
	[CPR_PRODUTO_CAMPANHA_ID] INT PRIMARY KEY IDENTITY(1,1),
	[CPR_CAMPANHA_PRODUTO_ID] INT NOT NULL,
	[CARTEIRA] VARCHAR(60) NULL,
	[URL_IMAGEM] VARCHAR(250) NULL,
	[DATA_CRIACAO] DATETIME DEFAULT(GETDATE()) NOT NULL,
	[DATA_ALTERACAO] DATETIME NULL,
	[ATIVO] BIT DEFAULT(0),
	CONSTRAINT [FK_CPR_PRODUTO_CAMPANHA_CPR_CAMPANHA_PRODUTO] FOREIGN KEY([CPR_CAMPANHA_PRODUTO_ID]) REFERENCES [dbo].[CPR_CAMPANHA_PRODUTO] ([CPR_CAMPANHA_PRODUTO_ID])
);


CREATE TABLE CPR_USUARIO_STATUS
(
	CPR_USUARIO_STATUS_ID INT PRIMARY KEY IDENTITY (1,1),			
	CPR_USUARIO_ID INT NOT NULL,
	GASTO_PERCENTUAL VARCHAR(10) NULL,
	GASTO DECIMAL (18,2),
	HABILITAR_TROCAR BIT NOT NULL DEFAULT(0),
	DATA_ATUALIZACAO DATETIME NULL,
    DATA_CRIACAO	 DATETIME DEFAULT(GETDATE()) NOT NULL
	
	CONSTRAINT [FK_CPR_USUARIO_ID]	FOREIGN KEY ([CPR_USUARIO_ID])	REFERENCES [dbo].[CPR_USUARIO] (CPR_USUARIO_ID)
);


--GÊNIO
INSERT INTO CPR_CAMPANHA_TIPO VALUES('Fase Catálogo Faixa')



--ALTERAÇÃO GÊNIO PARA TIPO CORRETO
UPDATE CPR_CAMPANHA SET CPR_CAMPANHA_TIPO_ID = 2 WHERE CPR_CAMPANHA_ID = 32

