USE DotzApp

GO


DECLARE @CAMPAIGN INT , @START DATETIME = DATEADD(month, DATEDIFF(month, 0,GETDATE()), 0), @PARTNER INT = 1153615 ;


IF NOT EXISTS (SELECT * FROM  CPR_CAMPANHA (NOLOCK) WHERE NOME LIKE '%Ciclo de Vida Alto Valor Pascoa%' AND ATIVO =1)
	BEGIN
		INSERT INTO CPR_CAMPANHA (NOME,DT_INICIO,DT_FIM,ATIVO,CPR_CAMPANHA_TIPO_ID,USUARIO_ID_PARCEIRO,GERAR_PREVISAO_FATURA_AUTOMATICO,GERAR_PREVISAO_FATURA_REALIZADO) 
						VALUES ('Ciclo de Vida Alto Valor Pascoa',@START, DATEADD(MONTH,3,@START),1,NULL,@PARTNER, 1,0)
		SET @CAMPAIGN = @@IDENTITY;
	END
ELSE
	BEGIN
		SET @CAMPAIGN = (SELECT CPR_CAMPANHA_ID FROM  CPR_CAMPANHA (NOLOCK) WHERE NOME LIKE '%Ciclo de Vida Alto Valor Pascoa%' AND ATIVO =1)
	END